feat(all_in_one): fuse app and push
MiPushFramework/MiPushFramework pull request #338
Opened 2020-10-11 14:37 UTC by TimothyZhang023

make one apk for user

Signed-off-by: zts1993 <zts1993@gmail.com>

2020-10-11 14:45 UTC, MlgmXyysd requested changes

2020-10-11 14:45 UTC, MlgmXyysd commented on push/src/main/AndroidManifest.xml
> +            android:value="true" />
According to https://github.com/MiPushFramework/MiPushFramework/commit/9a1174c155281423e10e75c10d9d59e5fe84aacd , there should be no more xposed module related content in Push. At the same time, the xposed function in push has been moved to a new independent software [MiPushEnhancement](https://github.com/MiPushFramework/MiPushEnhancement), and these residual codes should be deleted.

Reference: https://t.me/MiPushFramework/12

2020-10-11 19:40 UTC, Trumeet commented
Ohh that's so many changes...

2020-10-11 21:58 UTC, MlgmXyysd requested changes

2020-10-11 21:58 UTC, MlgmXyysd commented on push/src/main/res/values-zh/strings.xml
>      <string name="xposed_description">小米推送机型伪装插件，如需使用请开启</string>
There are still some remnants since the last change.

2020-10-25 04:58 UTC, Trumeet approved these changes
Seems good after some adjustments.

2020-10-25 04:58 UTC, merged